# Generated by Django 5.1.5 on 2025-02-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='date_added',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
